<<<<<<< HEAD
# Required metadata for SonarQube analysis
sonar.projectKey=your_project_key
sonar.organization=your_organization
sonar.host.url=https://sonarcloud.io

# Path to source files
sonar.sources=src

# Exclude files from analysis (optional)
sonar.exclusions=**/node_modules/**,**/*.test.js

# Encoding of the source code
sonar.sourceEncoding=UTF-8
=======
sonar.projectKey=3-rd-bca-23suca58_travel-itinerary-frontend
sonar.organization=3-rd-bca-23suca58


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=travel-itinerary-frontend
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
>>>>>>> 18bcd82d07a7cd6d328f941dd5181e21bc1a63c4
